Module: stinit
GROUP: 'DGROUP' YIE,YI,YIB,XIE,XI,XIB,_BSS,_DATA

Segment: _TEXT WORD USE32 00000000 bytes

Routine Size: 0 bytes,    Routine Base: _TEXT + 0000

No disassembly errors

Segment: _DATA WORD USE32 00000000 bytes

Segment: _BSS DWORD USE32 00000004 bytes
0000				___OpenStreams:

BSS Size: 4 bytes

Segment: XIB WORD USE32 00000000 bytes

Segment: XI WORD USE32 00000006 bytes
0000  00 20                                           . 
0002  00 00 00 00                                     DD	offset __InitFiles_

Segment: XIE WORD USE32 00000000 bytes

Segment: YIB WORD USE32 00000000 bytes

Segment: YI WORD USE32 00000006 bytes
0000  00 20                                           . 
0002  00 00 00 00                                     DD	offset __full_io_exit_

Segment: YIE WORD USE32 00000000 bytes

