Module: winglob
GROUP: 'DGROUP' CONST,CONST2,_DATA,_BSS

Segment: _TEXT BYTE USE32 00000000 bytes

Routine Size: 0 bytes,    Routine Base: _TEXT + 0000

No disassembly errors

Segment: CONST DWORD USE32 00000000 bytes

Segment: CONST2 DWORD USE32 00000000 bytes

Segment: _DATA DWORD USE32 0000004C bytes
0000				__ColorMap:
0000  00 00 00 00 00 00 A8 00 00 A8 00 00 00 A8 A8 00 ................
0010  A8 00 00 00 A8 00 A8 00 A8 54 00 00 A8 A8 A8 00 .........T......
0020  54 54 54 00 54 54 FF 00 54 FF 54 00 54 FF FF 00 TTT.TT..T.T.T...
0030  FF 54 54 00 FF 54 FF 00 FF FF 54 00 FF FF FF 00 .TT..T....T.....
0040				__MainWindowDestroyed:
0040  00 00 00 00                                     ....
0044				__AutoClearLines:
0044  40 42 0F 00                                     @B..
0048				__GotEOF:
0048  00 00 00 00                                     ....

Segment: _BSS DWORD USE32 0000001C bytes
0000				__ClassName:
0004				__MainWindow:
0008				__MainWindowData:
000C				__SubMenuEdit:
0010				__SubMenuWindows:
0014				__FixedFont:
0018				__MainMenu:

BSS Size: 28 bytes

